module siteProps
  let genderInput = "#genderGenderSeek"
  let postalCodeInput = "#postalCode"
  let viewSinglesButton = "View Singles"
  let emailRegisterInput = "[name='email']"
  let passwordRegisterInput = "[name='password']"
  let birthMonthInput = "#birthMonth"
  let birthDayInput = "#birthDay"
  let birthYearInput = "#birthYear"
  let handleInput = "[name='handle']"
  let emailLoginInput = "#email"
  let passwordLoginInput = "#password"
  let signOutNav = "N"
  let signOutButton = "Sign Out "
  let signInButton = "Sign in now »"
  let matchOptionClass = ".option"
  let favoriteMatchClass = ".cta-favorite"
  let favoritesButton = "F"
  let myFavesButton = "my faves "
  let favoriteCardsClass = ".cards"
  let addEntryVerifulUrl = "/matchbook/AddEntry.aspx"
